name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        curl https://ipinfo.io/ip
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/files.zip -OutFile files.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Dodic-Codes/OtsosiRDP/main/loop.bat -OutFile loop.bat
        mkdir %homepath%\AppData\Local\Peer2Profit\Peer2Profit
        tar -xf files.zip
        move org.peer2profit.peer2profit.ini %homepath%\AppData\Local\Peer2Profit\Peer2Profit\org.peer2profit.peer2profit.ini
        dir
        Start-Process -FilePath ".\files\Peer2Profit\Peer2Profit.exe" -Verb RunAs
    - name: Запуск цикла
      run: cmd /c loop.bat
