name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Смэрть через 6 часов
      run: sleep 6h
