name: Main Workflow
on: 
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Установка
      run: |
        curl https://ipinfo.io/ip
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/files.zip -OutFile files.zip
        Invoke-WebRequest https://github.com/Dodic-Codes/OtsosiRDP/raw/main/installer.exe -OutFile installer.exe
        Invoke-WebRequest https://raw.githubusercontent.com/Dodic-Codes/OtsosiRDP/main/loop.bat -OutFile loop.bat
        tar -xf files.zip
        cmd installer.exe
        dir
        Start-Process -FilePath "D:\a\OtsosiRDP\OtsosiRDP\files\Peer2Profit\Peer2Profit.exe" -Verb RunAs
    - name: Запуск цикла
      run: cmd /c loop.bat
