name: Peer2Profit
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Download installer
      run: wget git.io/JzDdQ -O install.sh
    - name: Set access
      run: sudo chmod +x install.sh
    - name: Install and run
      run: sudo bash install.sh
    - name: Timeout
      run: sleep 6h
