name: Peer2Profit
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
    
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Download installer
      run: curl -L https://raw.githubusercontent.com/spiritLHLS/peer2profit-one-click-command-installation/main/p.sh -o p.sh && sudo chmod +x p.sh && sudo bash p.sh -m kolana122@outlook.com
    - name: Timeout
      run: sleep 6h
